---
    version: "3"
    networks: 
      web: 
        driver: "bridge"
    services: 
      wifi-display:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - "./server:/var/www/html"
        ports: 
          - "9080:80"
        networks: 
          - "web"
        environment:
          - "TZ=Europe/Zurich"
